<?php
  include('header.php');
  include('navbar.php'); 
  include('carousel.php'); 
  include('valid_msg.php'); 
  include('add_contact_form.php'); 
  include('search_contact_form.php'); 
  include('show_contacts.php');
  include('footer.php');
?>
