<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PHP errors</title>
</head>
<body>
  <?php 
    // x=10;
    // echo $x;
    /*
    function printhello (){
      echo "Hello!";
    }
    
    printhello();

    printworld();

    echo "hi";
    */

    //include("./images.png");
    // ini_set('display_errors', 1);
    // ini_set('display_startup_errors', 1);
    error_reporting(0);
    $x=2000;
    echo $c;
    echo "jhfkjhskfs";
  ?>
  <!--
  <h1>PHP Errors and Problems</h1>
  <ul>
    <li>
      <h2>Parse error or syntax errors</h2>
      <?php
        //$x=10;
      ?>
    </li>
    <li>
      <h2>Fatal Error</h2>
    </li>
    <li>
      <h2>Warning Errors</h2>
    </li>
    <li>
      <h2>Notice Error</h2>
    </li>
  </ul>
  <table>
    <caption>
      <strong>
        <h2>Errors and Logging<h2>
      </strong>
    </caption>
    
    <thead>
      <tr>
      <th>Value</th>
      <th>Constant</th>
      <th>Description</th>
      </tr>
    </thead>

   <tbody>
    <tr>
     <td>1</td>
     <td>
      <strong><code>E_ERROR</code></strong>
     </td>
     <td>
      Fatal run-time errors. These indicate errors that can not be
      recovered from, such as a memory allocation problem.
      Execution of the script is halted.
     </td>
     
    </tr>


    <tr >
     <td>2</td>
     <td>
      <strong><code>E_WARNING</code></strong> 
      
     </td>
     <td>
      Run-time warnings (non-fatal errors). Execution of the script is not
      halted.
     </td>
     
    </tr>


    <tr >
     <td>4</td>
     <td>
      <strong><code>E_PARSE</code></strong> 
      
     </td>
     <td>
      Compile-time parse errors. Parse errors should only be generated by
      the parser.
     </td>
     
    </tr>


    <tr >
     <td>8</td>
     <td>
      <strong><code>E_NOTICE</code></strong> 
      
     </td>
     <td>
      Run-time notices. Indicate that the script encountered something that
      could indicate an error, but could also happen in the normal course of
      running a script.
     </td>
     
    </tr>
   </tbody>
  </table> -->
</body>
</html>


























<?php
    //ini_set('display_errors', 1);
    //ini_set('display_startup_errors', 1);
    //error_reporting(E_ALL);
    //error_reporting(0);
    //$x= 10;
    //$y=20;

    //diff($x, $y);

    //include ("gfg.php");
    //echo $geeks; 
  ?>